version: "3.7"

services:
  gitea:
    image: gitea/gitea:1.10
    container_name: gitea
    hostname: gitea
    ports:
      - 22:22/tcp
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ${VOLUME_PREFIX}/gitea:/data
    networks:
      - default
    labels:
      - traefik.http.routers.gitea.rule=Host(`git${HOST_DOMAIN}`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=leresolver
      - traefik.http.services=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    hostname: gogs
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ${VOLUME_PREFIX}/gogs:/data
    networks:
      - default
    labels:
      - traefik.http.routers.gogs.rule=Host(`gogs${HOST_DOMAIN}`)
      - traefik.http.routers.gogs.entrypoints=websecure
      - traefik.http.routers.gogs.tls=true
      - traefik.http.routers.gogs.tls.certresolver=leresolver
      - traefik.http.services=gogs
      - traefik.http.services.gogs.loadbalancer.server.port=3000
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    hostname: mongodb
    command: mongod --auth --smallfiles --nojournal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SECRETPERSONAL}
    volumes:
      - ${VOLUME_PREFIX}/mongo:/data/db
    labels:
      - traefik.tcp.routers.mongo.rule=HostSNI(`mongo${HOST_DOMAIN}`)
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SECRETPERSONAL}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${SECRETPERSONAL}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - ${VOLUME_PREFIX}/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    labels:
      - traefik.tcp.routers.mysql.rule=HostSNI(`mysql${HOST_DOMAIN}`)
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    hostname: redis
    command: redis-server --requirepass ${SECRETPERSONAL}
    volumes:
      - ${VOLUME_PREFIX}/redis:/data
    ports:
      - 6379:6379
    labels:
      - traefik.tcp.routers.redis.rule=HostSNI(`redis${HOST_DOMAIN}`)
  postgres:
    image: postgres:alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${SECRETPERSONAL}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ${VOLUME_PREFIX}/postgres:/var/lib/postgresql/data
      - ${VOLUME_PREFIX}/key/postgres/server.crt:/var/lib/postgresql/server.crt:ro
      - ${VOLUME_PREFIX}/key/postgres/server.key:/var/lib/postgresql/server.key:ro
    command:
      [
        "postgres",
        "-c",
        "ssl=on",
        "-c",
        "ssl_cert_file=/var/lib/postgresql/server.crt",
        "-c",
        "ssl_key_file=/var/lib/postgresql/server.key",
      ]
    labels:
      - traefik.tcp.routers.postgres.rule=HostSNI(`postgres${HOST_DOMAIN}`)
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    hostname: influxdb
    restart: always
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${DATABASE_USER}
      - INFLUXDB_ADMIN_PASSWORD=${SECRETPERSONAL}
      - INFLUXDB_USER=${DATABASE_USER}-user
      - INFLUXDB_USER_PASSWORD=${SECRETPERSONAL}
      - INFLUXDB_DB=${DATABASE_NAME}
    ports:
      - 2003:2003
    volumes:
      - ${VOLUME_PREFIX}/influxdb:/var/lib/influxdb
    networks:
      - default
    labels:
      - traefik.http.routers.influxdb.rule=Host(`influxdb${HOST_DOMAIN}`)
      - traefik.http.routers.influxdb.entrypoints=websecure
      - traefik.http.routers.influxdb.tls=true
      - traefik.http.routers.influxdb.tls.certresolver=leresolver
      - traefik.http.services=influxdb
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
      - traefik.tcp.routers.influxdb.rule=HostSNI(`influxdb${HOST_DOMAIN}`)
  chronograf:
    image: chronograf:alpine
    container_name: chronograf
    hostname: chronograf
    restart: always
    volumes:
      - ${VOLUME_PREFIX}/chronograf:/var/lib/chronograf
    networks:
      - default
    labels:
      - traefik.http.routers.chronograf.rule=Host(`chronograf${HOST_DOMAIN}`)
      - traefik.http.routers.chronograf.entrypoints=websecure
      - traefik.http.routers.chronograf.tls=true
      - traefik.http.routers.chronograf.tls.certresolver=leresolver
      - traefik.http.services=chronograf
      - traefik.http.services.chronograf.loadbalancer.server.port=8888
  frps:
    image: docker-tutorial:frps
    build:
      context: frp/frps
      dockerfile: Dockerfile
    container_name: frps
    hostname: frps
    restart: always
    network_mode: host
    labels:
      - traefik.tcp.routers.frps.rule=HostSNI(`frps${HOST_DOMAIN}`)
  frpc:
    image: docker-tutorial:frpc
    build:
      context: frp/frps
      dockerfile: Dockerfile
    container_name: frpc
    hostname: frpc
    restart: always
    network_mode: host
    volumes:
      - ./frp/frpc/frpc.ini:/app/frpc.ini
    labels:
      - traefik.enable=false
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: always
    hostname: netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    labels:
      - traefik.http.routers.netdata.rule=Host(`netdata${HOST_DOMAIN}`)
      - traefik.http.routers.netdata.entrypoints=websecure
      - traefik.http.routers.netdata.tls=true
      - traefik.http.routers.netdata.tls.certresolver=leresolver
      - traefik.http.services=netdata
      - traefik.http.services.netdata.loadbalancer.server.port=19999
  shadowsocks-proxy:
    image: nginx:dev
    container_name: shadowsocks
    restart: always
    hostname: shadowsocks
    build: $PWD/shadowsocks-proxy
    ports:
      - ${SHADOWSOCKS_PORT}:${SHADOWSOCKS_PORT}
    labels:
      - traefik.tcp.routers.ssproxy.rule=HostSNI(`ss${HOST_DOMAIN}`)
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest
    container_name: shadowsocks
    restart: always
    hostname: shadowsocks
    environment:
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=${SECRETPERSONAL}
    ports:
      - ${SHADOWSOCKS_PORT}:8388
    labels:
      traefik.enable: false
networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-webproxy}
